= Noteshare V2
:numbered:
:toc2:

== Plans

. Reader
.. Scrolling

.. Add search to index

.. Link search to show page

.. Add glossary and index to Reader

. Editor

.. Build new document

.. Build entry page

.. Figure out how to link

.. Could this be better built in Node?

. Renderer

.. Make this a separate based on JSON API

.. Could this be better built in Node?

. Image handler

.. Could this be better built in Node?

. Exporter

. Print Handler

. User

. Group

. Site

. Permissions

. Usage stats

. Likes

. Publishing

. Admin

== Commands

=== Postgres

----
psql -U carlson postgres

SELECT title, author, subdoc_refs, doc_refs FROM documents;
INSERT INTO documents (title, author) VALUES ('Intro to Magic', 'Z. Umlaut');
INSERT INTO documents (title, author, subdoc_refs) VALUES ('The Red Wall', 'Morlen Du', '{444, 555, 666}')
----



=== GIT

To remove the file from the repo and not delete it from the local file system use
`git rm --cached file.txt`

== Links

http://www.postgresql.org/docs/current/interactive/indexes-partial.html[postgres partial index] +
http://lucaguidi.com/2014/12/23/2014-retrospective-a-year-of-lotus.html[Lotus retrospective] +
https://www.binpress.com/tutorial/building-a-robust-json-api-client-with-ruby/140[Lotus JSON API] +
https://gitter.im/lotus/chat[Gitter Chat] +
https://github.com/lotus/model/blob/master/lib/lotus/entity/dirty_tracking.rb#L69[Dirty records] +
https://www.oreilly.com/ideas/4-reasons-why-microservices-resonate?utm_campaign=LaunchBit&utm_medium=email&utm_source=LaunchBit&utm_content=bsa-carbon&cmp=ba-prog-newsletter-article-lgen_lb_programming_site_launch_microsvcs[Microservices] +
http://techoctave.com/c7/posts/25-rails-request-environment-variables/[Rails Request Environment Variables] +
http://arjanvandergaag.nl/blog/up-and-running-with-lotus.html[Up and running with Lotus] + 
http://teotti.com/rails-vs-lotus/[Rails vs Lotus] + 
http://kimh.github.io/blog/en/lotus/creating-web-application-with-ruby-lotus[Kimh on crafting web apps] + 
https://elements.heroku.com/buttons/stevehook/lotus-todo[Lotus to-do on Heroku] + 
https://www.amberbit.com/blog/2014/9/29/10-skills-that-will-make-you-better-ruby-developer/[Becoming a better Rubyist]
http://solnic.eu/2015/06/06/cutting-corners-or-why-rails-may-kill-ruby.html[Is Rails killing Ruby?] + 
http://www.rubydoc.info/gems/slim/frames[Slim] + 
bundle exec lotus server --no-code-reloading
git remote set-url origin git@github.com:jxxcarlson/noteshare.git
https://github.com/slim-template/slim#output-without-html-escaping-[Slim, HTML escaping] + 
https://freezeapp.net/[Amazon Glacier] +
http://arjanvandergaag.nl/blog/up-and-running-with-lotus.html[Up and runing with Lotus] + 
http://blog.endpoint.com/2012/06/detecting-postgres-sql-injection.html[SQL Injection Attacks] + 

cat /usr/local/var/postgres/postmaster.pid
kill PID

pgstart
ps wax | grep `head -1 /usr/local/var/postgres/postmaster.pid`
http://sequel.jeremyevans.net/documentation.html[Sequel] + 
B = Sequel.connect('postgres://carlson:Lenus.417.Kamiah@localhost:5432/noteshare_development')
[4] pry(main)> dataset = DB['select id from documents']
=> #<Sequel::Postgres::Dataset: "select id from documents">
[5] pry(main)> dataset.count
=> 12


.jsonb coercer
----
require 'lotus/model/coercer'
require 'sequel'
require 'sequel/extensions/pg_json'

class PGJsonb < Lotus::Model::Coercer
  def self.dump(value)
    ::Sequel.pg_jsonb(value)
  end

  def self.load(value)
    ::Kernel.Hash(value) unless value.nil?
  end
end
----

https://css-tricks.com/how-css-selectors-work/[CSS Selectors] + 
https://learn.jquery.com/ajax/[AJAX] + 
git grep "string" $(git rev-list --all)
Ruby struct: http://blog.steveklabnik.com/posts/2012-09-01-random-ruby-tricks--struct-new
Rack:: https://github.com/lotus/lotus/blob/master/lib/lotus/action/csrf_protection.rb#L65
http://ruby.awsblog.com/post/Tx354Y6VTZ421PJ/-Downloading-Objects-from-Amazon-span-class-matches-S3-span-using-the-AWS-SDK-fo[Download from s3]
http://jasonseifer.com/2010/04/06/rake-tutorial[Rack Tutorial]
https://ruby.awsblog.com/post/Tx1K43Z7KXHM5D5/Uploading-Files-to-Amazon-S3[Upload Files to S3]
http://www.rubyinside.com/simple-file-upload-to-amazon-s3-from-ruby-313.html[Simple file upload to S3]
http://stackoverflow.com/questions/20724470/cors-issue-getting-error-no-access-control-allow-origin-header-is-present-w
https://www.designedbyaturtle.co.uk/2013/direct-upload-to-s3-with-a-little-help-from-jquery/
https://aws.amazon.com/articles/1434
heroku pg:psql --app nslab DATABASE
http://danwin.com/2013/03/ruby-minitest-cheat-sheet/
http://blog.teamtreehouse.com/short-introduction-minitest
ff
http://html5doctor.com/storing-data-the-simple-html5-way-and-a-few-tricks-you-might-not-have-known/[Javascript Persistent]
http://lucaguidi.com/2015/11/24/json-api-apps-with-lotus.html[Lotus and JSON API]
http://chriskottom.com/blog/2014/12/command-line-flags-for-minitest-in-the-raw/[Minitest]
http://metaskills.net/2015/02/08/customizing-rake-tasks-in-rails-41-and-higher/[rake test]
http://www.fozworks.com/blog/2007/04/16/rake-task-to-run-a-custom-group-of-tests/[Custom rake tests]
http://www.rubydoc.info/github/jnicklas/capybara[Capybara]
https://github.com/redpen-cc/redpen/pull/514[Red Pen Asciidoc Parser Project]
https://github.com/Mogztter/asciidoctor-fast-live-reload[Guillaume's project]
http://stackoverflow.com/questions/16917476/what-assertion-functions-are-there-in-minitest-spec[Minitest assertions]
http://elegantbrew.tumblr.com/post/36238889587/reading-minitest-wrap-up[Elegant brew on minitest]
heroku pg:psql --app nslab DATABASE
http://www.rubydoc.info/gems/asciidoctor/Asciidoctor/AbstractBlock#find_by-instance_method[Asciidoctor parser - sections]
https://robots.thoughtbot.com/rspec-integration-tests-with-capybara[Integration testing with Capybara]
// http://rectangleworld.com/blog/archives/15[Moving objects with Javascript]
http://www.webreference.com/programming/javascript/mk/column2/index.html
https://github.com/bevacqua/dragula#demo[Dragula]
npm install dragula --save
http://alan.blog-city.com/jquerylinedtextarea.htm[Jquery line numbers in textarea]
http://climber2002.github.io/blog/2015/03/29/customize-devise-to-support-subdomain-authentication/[warden, multitenancy]
https://gorails.com/forum/structure-guidance-multi-tenancy-authentication-authorization[Multi tenancy authentication]
http://stackoverflow.com/questions/10402777/share-session-cookies-between-subdomains-in-rails[share session cookies among subdomains] -- IMPORTANT
http://pothibo.com/2013/07/authentication-with-warden-devise-less/[Good Warden guide]
https://github.com/radar/guides/tree/master/warden[Good article on Warden]
https://basecamp.com/open-source[Basecamp open source]
https://github.com/railsware/rack_session_access[rack session access for testing]
http://codetunes.com/2009/dynamic-cookie-domains-with-racks-middleware/[Set cookies with rack for domains]
https://github.com/lotus/controller/blob/master/lib/lotus/action/cookies.rb#L53[Lotus cookies]
https://github.com/lotus/controller/blob/master/lib/lotus/action/cookie_jar.rb#L74[Lotus cookies 2]
https://en.wikipedia.org/wiki/HTTP_cookie[Wikipedia: cookies]
http://codefol.io/posts/when-should-you-not-use-heroku[when not to use Heroku]
http://stackoverflow.com/questions/3295083/how-do-i-set-a-cookie-with-a-ruby-rack-middleware-component[setting rack cookies]
http://chneukirchen.org/repos/rack/lib/rack/session/cookie.rb[excellent code for rack session cookie]
http://www.rubydoc.info/github/rack/rack/Rack/Session/Cookie[rubydoc rack session cookie]
http://chneukirchen.org/blog/archive/2007/02/introducing-rack.html[Introducing Rack (Blog Post, EXCELLENT!)]
http://rack.github.io/[rack @ Github]
https://github.com/rack/rack/wiki[rack wiki]
http://rubylearning.com/blog/2013/04/02/whats-rack/[Excellent rack tutoria by Satish Talim 5 stars]
http://stackoverflow.com/questions/5123325/correct-way-to-share-login-sessions-across-subdomains-in-rails-3[Important SO article on sharing session keys]
https://player.vimeo.com/video/71846170[Engineyard Demo]
https://robots.thoughtbot.com/write-reliable-asynchronous-integration-tests-with-capybara[Integration tests with Capybara]
http://stackoverflow.com/questions/3388511/run-rake-tasks-in-sequence[sequence rake tasks]
https://blog.heroku.com/archives/2013/6/5/javascript_in_your_postgres[javascript in postgres]
http://stackoverflow.com/questions/34481638/how-to-use-tocify-with-asciidoctor-for-a-dynamic-toc[tocify -- collapsilble toc]
https://github.com/davydovanton/lotus-webpack-reactjs[Lotus app with react.js (davydovanton)]
https://github.com/solnic/lotuskase[Solnic's Lotus app]
http://lotusrb.org/blog/2015/12/29/introducing-assets.html[Lotus assets]
bundle exec lotus db create
http://www.copterlabs.com/json-what-it-is-how-it-works-how-to-use-it/[JSON - How to use it]
https://github.com/jodosha/mruby-rack-json-api[MRuby reall fast JSON API app (Lotus - Jodosha)

http://redis.io/topics/quickstart[Redis quick start]
http://redis.io/topics/data-types-intro[data structures]
https://feeding.cloud.geek.nz/posts/restoring-single-table-from-postgres/[Restoring a single table in Postgres]
To export the vschool database:
heroku pg:backups capture
$ curl -o latest.dump `heroku pg:backups public-url`
https://www.safaribooksonline.com/library/view/heroku-up-and/9781449341381/ch05.html[heroku book on postgres]
https://devcenter.heroku.com/articles/ruby-memory-use[Heroku: memory problems]
https://docs.newrelic.com/docs/agents/ruby-agent/frameworks/sinatra-support[NewRelic for RACK apps]
