= Noteshare V2
:numbered:
:toc2:

== Plans

. Reader
.. Scrolling

.. Add search to index

.. Link search to show page

.. Add glossary and index to Reader

. Editor

.. Build new document

.. Build entry page

.. Figure out how to link

.. Could this be better built in Node?

. Renderer

.. Make this a separate based on JSON API

.. Could this be better built in Node?

. Image handler

.. Could this be better built in Node?

. Exporter

. Print Handler

. User

. Group

. Site

. Permissions

. Usage stats

. Likes

. Publishing

. Admin

== Commands

=== Postgres

----
psql -U carlson postgres

SELECT title, author, subdoc_refs, doc_refs FROM documents;
INSERT INTO documents (title, author) VALUES ('Intro to Magic', 'Z. Umlaut');
INSERT INTO documents (title, author, subdoc_refs) VALUES ('The Red Wall', 'Morlen Du', '{444, 555, 666}')
----



=== GIT

To remove the file from the repo and not delete it from the local file system use
`git rm --cached file.txt`

== Links

http://www.postgresql.org/docs/current/interactive/indexes-partial.html[postgres partial index] +
http://lucaguidi.com/2014/12/23/2014-retrospective-a-year-of-lotus.html[Lotus retrospective] +
https://www.binpress.com/tutorial/building-a-robust-json-api-client-with-ruby/140[Lotus JSON API] +
https://gitter.im/lotus/chat[Gitter Chat] +
https://github.com/lotus/model/blob/master/lib/lotus/entity/dirty_tracking.rb#L69[Dirty records] +
https://www.oreilly.com/ideas/4-reasons-why-microservices-resonate?utm_campaign=LaunchBit&utm_medium=email&utm_source=LaunchBit&utm_content=bsa-carbon&cmp=ba-prog-newsletter-article-lgen_lb_programming_site_launch_microsvcs[Microservices] +
http://techoctave.com/c7/posts/25-rails-request-environment-variables/[Rails Request Environment Variables] +
http://arjanvandergaag.nl/blog/up-and-running-with-lotus.html[Up and running with Lotus] + 
http://teotti.com/rails-vs-lotus/[Rails vs Lotus] + 
http://kimh.github.io/blog/en/lotus/creating-web-application-with-ruby-lotus[Kimh on crafting web apps] + 
https://elements.heroku.com/buttons/stevehook/lotus-todo[Lotus to-do on Heroku] + 
https://www.amberbit.com/blog/2014/9/29/10-skills-that-will-make-you-better-ruby-developer/[Becoming a better Rubyist]
http://solnic.eu/2015/06/06/cutting-corners-or-why-rails-may-kill-ruby.html[Is Rails killing Ruby?] + 
http://www.rubydoc.info/gems/slim/frames[Slim] + 
bundle exec lotus server --no-code-reloading
git remote set-url origin git@github.com:jxxcarlson/noteshare.git
https://github.com/slim-template/slim#output-without-html-escaping-[Slim, HTML escaping] + 
https://freezeapp.net/[Amazon Glacier] +
http://arjanvandergaag.nl/blog/up-and-running-with-lotus.html[Up and runing with Lotus] + 
http://blog.endpoint.com/2012/06/detecting-postgres-sql-injection.html[SQL Injection Attacks] + 

cat /usr/local/var/postgres/postmaster.pid
kill PID

pgstart
ps wax | grep `head -1 /usr/local/var/postgres/postmaster.pid`
http://sequel.jeremyevans.net/documentation.html[Sequel] + 
B = Sequel.connect('postgres://carlson:Lenus.417.Kamiah@localhost:5432/noteshare_development')
[4] pry(main)> dataset = DB['select id from documents']
=> #<Sequel::Postgres::Dataset: "select id from documents">
[5] pry(main)> dataset.count
=> 12


.jsonb coercer
----
require 'lotus/model/coercer'
require 'sequel'
require 'sequel/extensions/pg_json'

class PGJsonb < Lotus::Model::Coercer
  def self.dump(value)
    ::Sequel.pg_jsonb(value)
  end

  def self.load(value)
    ::Kernel.Hash(value) unless value.nil?
  end
end
----

